data_ingestion:
  raw_zip_path: "/usr/local/airflow/include/artifact/download/zip/"
  zip_name: "network.zip"
  raw_csv_path: "/usr/local/airflow/include/artifact/download/csv/"
  dataset_url: "https://www.kaggle.com/api/v1/datasets/download/chethuhn/network-intrusion-dataset"
  raw_path: "/usr/local/airflow/include/artifact/data/raw"
  file_name: "rawdata.csv"
  processed_path: "/usr/local/airflow/include/artifact/data/processed/"

data_transform:
  file_path: "/usr/local/airflow/include/artifact/data/processed/"
  transformed_path: "/usr/local/airflow/include/artifact/data/transformed/"
  model_path: "/usr/local/airflow/include/artifact/transformedmodels"
  features_pkl_name: "selected_features.pkl"
  target_col: "Label"

model_training:
  transformed_path: "artifact/data/transformed/"
  target_col: "Label"
  model_path: "artifact/models/"

model_evaluating:
  test_dir: "artifact/data/transformed/test_transformed.csv"
  model_path: "artifact/models"
  model_name: "best_model.pkl"
  metrics_file: "metrics.json"
  tracking_uri: "https://dagshub.com/DevManpreet5/network_Security_end2toend.mlflow"
  target_col: "Label"
