data_ingestion:
  raw_zip_path: "artifact/download/zip/"
  zip_name: "network.zip"
  raw_csv_path: "artifact/download/csv/"
  dataset_url: "https://www.kaggle.com/api/v1/datasets/download/chethuhn/network-intrusion-dataset"
  raw_path: "artifact/data/raw"
  file_name: "rawdata.csv"
  processed_path: "artifact/data/processed/"

data_transform:
  file_path: "artifact/data/processed/"
  transformed_path: "artifact/data/transformed/"
  model_path: "artifact/transformedmodels"
  features_pkl_name: "selected_features.pkl"
  target_col: "Label"

model_training:
  transformed_path: "artifact/data/transformed/"
  target_col: "Label"
  model_path: "artifact/models/"
